[project]
name = "syno-helper"
version = "0.1.0"
description = "A helper tool to automatically upload/renew certificates from ACME json to Synology NAS"
readme = "README.md"
authors = [
    { name = "lex.xu", email = "shuangrain07@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "pyotp>=2.8.0",
    "synology-api>=0.9.3",
]

[project.scripts]
syno-helper = "syno_helper.main:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
